# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    tags: ["v*"]
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add Bintray Secret
      run: |
        echo "bintray.apikey=${{ secrets.BINTRAY_APIKEY }}" >> local.properties
        echo "bintray.user=${{ secrets.BINTRAY_USER }}" >> local.properties
        echo "bintray.gpg.password=${{ secrets.BINTRAY_GPG_PASSWORD }}" >> local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#     - name: Build with Gradle
#       run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Upload to Bintray
      run: |
        ./gradlew install
#        ./gradlew bintrayUpload
    - name: Publish to Release
      env: 
        GITHUB_TOKEN: ${{ secrets.GIT_RELEASE_TOKEN_RIPPLE_CHECK_BOX }}
      run: |
        tag_name="${GITHUB_REF##*/}"
        hub release create -a "sample/build/outputs/apk/debug/app-debug.apk" -a "ripple-checkbox/build/outputs/aar/ripple-checkbox-release.aar" -m "$tag_name" "$tag_name"
